# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines.yml

pool:
  vmImage: 'ubuntu-latest'

steps:

# Azure Key Vault
# Download Azure Key Vault secrets
- task: AzureKeyVault@1
  displayName: 'Download Connection Secrets from Azure Key Vault'
  inputs:
    azureSubscription: Azure
    keyVaultName: DevOps-Terraform-KV
- task: TerraformInstaller@0
  displayName: 'Install Terraform Version $(TERRAFORM-VERSION)'
  inputs:
    terraformVersion: '$(TERRAFORM-VERSION)'
- script: terraform init -get=true -upgrade=true -backend-config='storage_account_name=$(sa-name)' -backend-config='container_name=$(blob-name)' -backend-config='access_key=$(sa-key)' -backend-config='key=$(state-key)'
  workingDirectory: '$(Build.SourcesDirectory)/aks'
  displayName: 'Initalize Terraform'
- script: 'terraform validate'
  workingDirectory: '$(Build.SourcesDirectory)/aks'
  displayName: 'Validate Terraform Code'
- script: 'terraform plan -lock=true -out=terraform.plan'
  displayName: 'Terraform Dry Run (Plan)'
  workingDirectory: '$(Build.SourcesDirectory)/aks'