# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: [master]
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:

# Azure Key Vault
# Download Azure Key Vault secrets
- task: AzureKeyVault@1
  inputs:
    azureSubscription: Azure
    keyVaultName: DevOps-Terraform-KV
- task: TerraformInstaller@0
  inputs:
    terraformVersion: '$TERRAFORM-VERSION'